---
services:
  qbittorrent:
    # https://docs.linuxserver.io/images/docker-qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - /<yourpath>/config:/config
      - /<yourpath>/downloads:/downloads
    environment:
      - TZ=Etc/UTC
    networks:
      - default
      - vpn

  qbittorrent-natmap:
    # https://github.com/epicofficer/qbittorrent-natmap
    image: ghcr.io/epicofficer/qbittorrent-natmap:latest
    container_name: qbittorrent-natmap
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Etc/UTC
      # - QBITTORRENT_SERVER=
      # - QBITTORRENT_PORT=80
      # - QBITTORRENT_USER=admin
      # - QBITTORRENT_PASS=adminadmin
      # - VPN_GATEWAY=
      # - VPN_IF_NAME=wg0
      # - CHECK_INTERVAL=60
      # - NAT_LEASE_LIFETIME=60
    cap_add:
      - NET_ADMIN
    network:
      - default
      - vpn
    depends_on:
      qbittorrent:
        condition: service_started

networks:
  default:
    internal: true
  vpn:
    name: wg0
    external: true